### ISSUE TITLE
pip install fistpy UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 874: illegal multibyte sequence

### ISSUE THREAD

**Issue by QGB** [puria/fistpy#2]
```
pip install fistpy
Collecting fistpy
  Downloading fistpy-0.0.4.tar.gz (4.5 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\QGB\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\qgb\\AppData\\Local\\Temp\\pip-install-058hhpeo\\fistpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\qgb\\AppData\\Local\\Temp\\pip-install-058hhpeo\\fistpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\qgb\AppData\Local\Temp\pip-install-058hhpeo\fistpy\pip-egg-info'
         cwd: C:\Users\qgb\AppData\Local\Temp\pip-install-058hhpeo\fistpy\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\qgb\AppData\Local\Temp\pip-install-058hhpeo\fistpy\setup.py", line 8, in <module>
        LONG_DESCRIPTION = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 874: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Note: you may need to restart the kernel to use updated packages.
```

**Comment by puria** [comment]
Never tried on windows... seems an OS problem! Will dig as soon as I have access to a win machine
